### ISSUE TITLE
Yaml and boolean in config files

### ISSUE THREAD

**Issue by guiguem** [project8/katydid#69]
It seems that the boolean parameters in a yam file are not taken into account/set to "true" even if the value in the config file is "true", "false", "no", "TRUE".

**Comment by nsoblath** [comment]
I'm unable to replicate this problem.  I created branch hotfix/2.6.1 to deal with this.  Please use it for testing, as there were other things with the test programs that I needed to fix.

Can you try these steps:

1. Checkout hotfix/2.6.1 and do a recursive submodule update
1. In CMake set Scarab_ENABLE_EXECUTABLES and Scarab_ENABLE_TESTING to true
1. Rebuild
1. Save this file in your build directory & remove the `.txt` extra extension that Github forced me to add: 
[test_file.yaml.txt](https://github.com/project8/katydid/files/475610/test_file.yaml.txt)
1. Run `> bin/test_yaml test_file.yaml`

**Comment by nsoblath** [comment]
The problem turned out to be in scarab::param_value.  When the value is stored as a string, but extracted as a bool, it always returned true unless the string was empty.  This policy means that "false" or "0" will still return true.

I've changed it so now the following will return false:
- ""
- "0"
- "false" [and any capitalization variation]
- [any string that doesn't start with "true" and any capitalization variation]

And the following will return true
- "1" and any integer with numeric characters only
- "true" [and any capitalization variation]
- [any string starting with "true" and any capitalization variation]
